--
-- PostgreSQL database dump
--

\restrict 7PCcMzYebpErcDNtL3fd48vcbHMd5I9hQxerCtMSA2ifeKiSuH85BSSEsDYb9PG

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fakture; Type: DATABASE; Schema: -; Owner: app_user
--

CREATE DATABASE fakture WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE fakture OWNER TO app_user;

\unrestrict 7PCcMzYebpErcDNtL3fd48vcbHMd5I9hQxerCtMSA2ifeKiSuH85BSSEsDYb9PG
\connect fakture
\restrict 7PCcMzYebpErcDNtL3fd48vcbHMd5I9hQxerCtMSA2ifeKiSuH85BSSEsDYb9PG

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clients; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.clients (
    company_id uuid NOT NULL,
    client_id uuid NOT NULL
);


ALTER TABLE public.clients OWNER TO app_user;

--
-- Name: companies; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.companies (
    id uuid DEFAULT uuidv7() NOT NULL,
    full_name character varying NOT NULL,
    short_name character varying,
    company_id character varying NOT NULL,
    tax_id character varying NOT NULL,
    address character varying NOT NULL,
    country character varying NOT NULL,
    city character varying NOT NULL,
    zip character varying NOT NULL,
    phone character varying,
    email character varying
);


ALTER TABLE public.companies OWNER TO app_user;

--
-- Name: COLUMN companies.company_id; Type: COMMENT; Schema: public; Owner: app_user
--

COMMENT ON COLUMN public.companies.company_id IS 'Maticni broj';


--
-- Name: COLUMN companies.tax_id; Type: COMMENT; Schema: public; Owner: app_user
--

COMMENT ON COLUMN public.companies.tax_id IS 'Poreski Identifikacioni Broj';


--
-- Name: invoice_items; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.invoice_items (
    id bigint NOT NULL,
    invoice_id uuid CONSTRAINT invoice_items_column_name_not_null NOT NULL,
    "order" integer NOT NULL,
    description character varying NOT NULL,
    unit character varying NOT NULL,
    quantity double precision NOT NULL,
    price money NOT NULL,
    tax double precision DEFAULT 0 NOT NULL
);


ALTER TABLE public.invoice_items OWNER TO app_user;

--
-- Name: COLUMN invoice_items.unit; Type: COMMENT; Schema: public; Owner: app_user
--

COMMENT ON COLUMN public.invoice_items.unit IS 'Jedinica mere';


--
-- Name: COLUMN invoice_items.price; Type: COMMENT; Schema: public; Owner: app_user
--

COMMENT ON COLUMN public.invoice_items.price IS 'Price per unit';


--
-- Name: invoice_items_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.invoice_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.invoices (
    id uuid DEFAULT uuidv7() NOT NULL,
    invoice_number character varying NOT NULL,
    company_id uuid NOT NULL,
    client_id uuid NOT NULL,
    date_created timestamp with time zone DEFAULT now(),
    turnover_date timestamp with time zone,
    payment_deadline time without time zone,
    value money NOT NULL
);


ALTER TABLE public.invoices OWNER TO app_user;



--
-- Name: invoice_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.invoice_items_id_seq', 2, true);


--
-- Name: clients clients_pk; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pk PRIMARY KEY (company_id, client_id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: invoice_items invoice_items_pk; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT invoice_items_pk PRIMARY KEY (id);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);


--
-- Name: invoices invoices_unique; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_unique UNIQUE (invoice_number);


--
-- Name: invoice_items_invioice_id_index; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX invoice_items_invioice_id_index ON public.invoice_items USING btree (invoice_id);


--
-- Name: clients clients_client_fk; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_client_fk FOREIGN KEY (client_id) REFERENCES public.companies(id);


--
-- Name: clients clients_company_fk; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: invoices invoices_client_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_client_id_fk FOREIGN KEY (client_id) REFERENCES public.companies(id);


--
-- Name: invoices invoices_company_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_company_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7PCcMzYebpErcDNtL3fd48vcbHMd5I9hQxerCtMSA2ifeKiSuH85BSSEsDYb9PG

